on:
  github:
    branches:
      only: main

jobs:

  cloneRepo:
    resources:
      instance-type: C4
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url
      ref: context.event.github.ref

  runAlgo:
    resources:
      instance-type: C4
    needs:
      - cloneRepo
    inputs:
      repo: cloneRepo.outputs.repo
    outputs:
      data:
        type: dataset
        with:
          ref: demo-dataset
    uses: script@v1
    with:
      script: |-
        python /inputs/repo/hello.py
        #cp -R /inputs/repo 
        #cd /nlp
        #pip3 install -U transformers
        #python3 nlp_text_generation.py
        #mv output.txt /outputs/generatedText
        #ls "-aFlR" /outputs/generatedText
      image: kamrondocker/trading
      #image: paperspace/transformers-gpu:0.4.0
