'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url
  HelloWorld:
    resources:
      instance-type: C5
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    outputs:
      data:
        type: dataset
        with:
          id: test-data
      # The container is responsible creating the file "/outputs/<name>" with the
      # content being a small-ish utf-8 encoded string.
      #echo2:
      #  type: string
    uses: script@v1
    with:
      script: python /inputs/repo/hello.py
      image: tensorflow/tensorflow:1.14.0-py3
